### ISSUE TITLE
There are many bugs and glitches that u should fix

### ISSUE THREAD

**Issue by Priyanshu348** [outlaylol/mee6-but-better#2]

**Comment by outlaylol** [comment]
True, I might update it...

**Comment by Priyanshu348** [comment]
Can u provide your discord Id

**Comment by outlaylol** [comment]
685675290176913504

**Comment by Priyanshu348** [comment]
My id is Hackerz#6969 add me as a friend

**Comment by outlaylol** [comment]
I think i've fixed most of the stuff in this repo, if there are any errors please feel free to open a new issue.
